version: '3.4'
services:
  db_development:
    build:
      context: .
      dockerfile: DOCKERFILE.db.development
    image: db_development
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DEVELOPMENT_POSTGRES_USER}
      - POSTGRES_DB=${DEVELOPMENT_POSTGRES_NAME}
      - POSTGRES_PASSWORD=${DEVELOPMENT_POSTGRES_PASSWORD}
  api_development:
    build:
      context: .
      dockerfile: DOCKERFILE.api.development
    image: api_development
    command: ./bin/development-docker-entrypoint.sh
    volumes:
      - .:/code
      - data:/data
    ports:
      - 8000:8000
    depends_on:
      - db_development
    environment:
      - PROJECT_NAME
      - DEBUG=True
      - POSTGRES_USER=${DEVELOPMENT_POSTGRES_USER}
      - POSTGRES_NAME=${DEVELOPMENT_POSTGRES_NAME}
      - POSTGRES_HOST=${DEVELOPMENT_POSTGRES_HOST}
      - POSTGRES_PORT=${DEVELOPMENT_POSTGRES_PORT}
      - POSTGRES_PASSWORD=${DEVELOPMENT_POSTGRES_PASSWORD}
      - DJANGO_SECRET_KEY=${DEVELOPMENT_DJANGO_SECRET_KEY}
      - AWS_ACCESS_KEY_ID=${DEVELOPMENT_AWS_ACCESS_KEY_ID} 
      - AWS_SECRET_ACCESS_KEY=${DEVELOPMENT_AWS_SECRET_ACCESS_KEY}

volumes:
  data:
