version: '3.4'
services:
  api_staging:
    build:
      context: .
      dockerfile: DOCKERFILE.api.staging
    image: api_staging
    command: ./bin/staging-docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - PROJECT_NAME
      - DEBUG=False
      - POSTGRES_USER=${STAGING_POSTGRES_USER}
      - POSTGRES_NAME=${STAGING_POSTGRES_NAME}
      - POSTGRES_HOST=${STAGING_POSTGRES_HOST}
      - POSTGRES_PORT=${STAGING_POSTGRES_PORT}
      - POSTGRES_PASSWORD=${STAGING_POSTGRES_PASSWORD}
      - DJANGO_SECRET_KEY=${STAGING_DJANGO_SECRET_KEY}
